server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jwtserver
    username: sa
    password:

  jpa:
    hibernate:
      hbm2ddl-auto: update #create update none
    show-sql: true
